#数据库
spring:
  datasource:
    url: jdbc:mysql://47.100.127.7:3306/top_fivice?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    #阿里数据库连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      stat-view-servlet:
        login-username: admin
        login-password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  #thymeleaf 配置
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    #缓存设置为false, 这样修改之后马上生效，便于调试
    cache: false
    prefix: classpath:/templates
    suffix: .html
#tomcat配置
server:
  servlet:
    context-path: /jpa
    session:
      timeout: 30m
  tomcat:
    max-threads: 200
    max-connections: 10000
    uri-encoding: UTF-8
  port: 8080
logging:
  file: springboot-jpa.log